POST http://localhost:3000/plantrip
Content-Type: application/json

{
  "tripName": "Grand Teton National Park",
  "tripDate": "2024-07-01",
  "tripLocation": "Wyoming",
  "tripDescription": "A week long trip to Grand Teton National Park. We will be camping and hiking in the park."
}